package configs

const (
	//AuditName ...
	AuditName = "audits-test"
	//AuditTimeout ...
	AuditTimeout = 350
	//AuditConnectionTimeout ...
	AuditConnectionTimeout = 500
	//AuditMaxWait ...
	AuditMaxWait = 350
	//AuditMaxConnections ...
	AuditMaxConnections = 100
	//AuditMaxConnectionsPerRoute ...
	AuditMaxConnectionsPerRoute = 30
	//AuditMaxRetries ..
	AuditMaxRetries = 3
	//AuditRetryDelay ...
	AuditRetryDelay = 30
)
